/**
 * 定义所有的action type
 * @type {string}
 */
// login模块
export const REQUEST_LOGIN='REQUEST_LOGIN';

export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

export const REQUEST_ERR = 'REQUEST_ERR';


// 标签页

export const REQUEST_TAGS = 'REQUEST_TAGS';

export const SAVE_TAGS = 'SAVE_TAGS';

export const CREATE_TAG = 'CREATE_TAG';

export const DELETE_TAG = 'DELETE_TAG';

export const CREATE_TAG_FAILED = 'CREATE_TAG_FAILED';

export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';

export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';

export const DELETE_TAG_FAILED = 'DELETE_TAG_FAILED';

export const REQUEST_TAGS_LOADING = 'REQUEST_TAGS_LOADING';

// 简历
export const REQUEST_RESUME = 'REQUEST_RESUME';

export const SUBMIT_RESUME = 'SUBMIT_RESUME';

export const SAVE_RESUME = 'SAVE_RESUME';

export const SUBMIT_RESUME_FAILED = 'SUBMIT_RESUME_FAILED';

export const SUBMIT_RESUME_SUCCESS = 'SUBMIT_RESUME_SUCCESS';

export const REQUEST_RESUME_FAILED = 'REQUEST_RESUME_FAILED';

export const REQUEST_RESUME_SUCCESS = 'REQUEST_RESUME_SUCCESS';


//新建文章
export const REQUEST_ARTICLE = 'REQUEST_ARTICLE';

export const SUBMIT_ARTICLE = 'SUBMIT_ARTICLE';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const EDITOR_ARTICLE = 'EDITOR_ARTICLE';

export const SAVE_ARTICLE_LIST = 'SAVE_ARTICLE_LIST';

export const SUBMIT_ARTICLE_FAILED = 'SUBMIT_ARTICLE_FAILED';

export const SUBMIT_ARTICLE_SUCCESS = 'SUBMIT_ARTICLE_SUCCESS';

export const REQUEST_ARTICLE_SUCCESS = 'REQUEST_ARTICLE_SUCCESS';

export const REQUEST_ARTICLE_FAILED = 'REQUEST_ARTICLE_FAILED';

export const DELETE_ARTICLE_FAILED = 'DELETE_ARTICLE_FAILED';

export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';

export const EDITOR_ARTICLE_FAILED = 'EDITOR_ARTICLE_FAILED';

export const EDITOR_ARTICLE_SUCCESS = 'EDITOR_ARTICLE_SUCCESS';

