/**
 * 定义所有的action type
 * @type {string}
 */
// login模块
export const REQUEST_LOGIN='REQUEST_LOGIN';

export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

export const REQUEST_ERR = 'REQUEST_ERR';


// 标签页

export const REQUEST_TAGS = 'REQUEST_TAGS';

export const SAVE_TAGS = 'SAVE_TAGS';

export const CREATE_TAG = 'CREATE_TAG';

export const DELETE_TAG = 'DELETE_TAG';

export const CREATE_TAG_FAILED = 'CREATE_TAG_FAILED';

export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';

export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';

export const DELETE_TAG_FAILED = 'DELETE_TAG_FAILED';

export const REQUEST_TAGS_LOADING = 'REQUEST_TAGS_LOADING';

// 简历
export const REQUEST_RESUME = 'REQUEST_RESUME';

export const SUBMIT_RESUME = 'SUBMIT_RESUME';

export const SAVE_RESUME = 'SAVE_RESUME';

export const SUBMIT_RESUME_FAILED = 'SUBMIT_RESUME_FAILED';

export const SUBMIT_RESUME_SUCCESS = 'SUBMIT_RESUME_SUCCESS';

export const REQUEST_RESUME_FAILED = 'REQUEST_RESUME_FAILED';

export const REQUEST_RESUME_SUCCESS = 'REQUEST_RESUME_SUCCESS';

// 留言
export const GET_COMMENT = 'GET_COMMENT';

export const GET_ALL_COMMENT = 'GET_ALL_COMMENT';

export const DELETE_COMMENT = 'DELETE_COMMENT';

export const CHANGE_STATE = 'CHANGE_STATE';

export const SAVE_PAGE = 'SAVE_PAGE';

export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';

export const SAVE_COMMENT = 'SAVE_COMMENT';

export const SAVE_ALL_COMMENT = 'SAVE_ALL_COMMENT';

export const SUBMIT_COMMENT_FAILED = 'SUBMIT_COMMENT_FAILED';

export const SUBMIT_COMMENT_SUCCESS = 'SUBMIT_COMMENT_SUCCESS';

export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED';

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';

export const CHANGE_STATE_SUCCESS = 'CHANGE_STATE_SUCCESS';

export const CHANGE_STATE_FAILED = 'CHANGE_STATE_FAILED';

export const GET_COMMENT_FAILED = 'GET_COMMENT_FAILED';

export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';

export const GET_ALL_COMMENT_FAILED = 'GET_ALL_COMMENT_FAILED';

export const GET_ALL_COMMENT_SUCCESS = 'GET_ALL_COMMENT_SUCCESS';

//新建文章
export const REQUEST_ARTICLE = 'REQUEST_ARTICLE';

export const SUBMIT_ARTICLE = 'SUBMIT_ARTICLE';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const GET_ARTICLE = 'GET_ARTICLE';

export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';

export const SAVE_ARTICLE_LIST = 'SAVE_ARTICLE_LIST';

export const SAVE_ARTICLES_LIST = 'SAVE_ARTICLES_LIST';

export const SAVE_ARTICLE_CONTENT = 'SAVE_ARTICLE_CONTENT';

export const SAVE_ARTICLE_PAGE = 'SAVE_ARTICLE_PAGE';

export const SUBMIT_ARTICLE_FAILED = 'SUBMIT_ARTICLE_FAILED';

export const SUBMIT_ARTICLE_SUCCESS = 'SUBMIT_ARTICLE_SUCCESS';

export const REQUEST_ARTICLE_SUCCESS = 'REQUEST_ARTICLE_SUCCESS';

export const REQUEST_ARTICLE_FAILED = 'REQUEST_ARTICLE_FAILED';

export const DELETE_ARTICLE_FAILED = 'DELETE_ARTICLE_FAILED';

export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';

export const GET_ARTICLE_FAILED = 'GET_ARTICLE_FAILED';

export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';

export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';

export const GET_LIST_FAILED = 'GET_LIST_FAILED';

