/**
 * 定义所有的action type
 * @type {string}
 */
// login模块
export const REQUEST_LOGIN='REQUEST_LOGIN';

export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

export const REQUEST_ERR = 'REQUEST_ERR';


// 标签页

export const REQUEST_TAGS = 'REQUEST_TAGS';

export const SAVE_TAGS = 'SAVE_TAGS';

export const CREATE_TAG = 'CREATE_TAG';

export const DELETE_TAG = 'DELETE_TAG';

export const CREATE_TAG_FAILED = 'CREATE_TAG_FAILED';

export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';

export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';

export const DELETE_TAG_FAILED = 'DELETE_TAG_FAILED';

export const REQUEST_TAGS_LOADING = 'REQUEST_TAGS_LOADING';

// 简历
export const REQUEST_RESUME = 'REQUEST_RESUME';

export const SUBMIT_RESUME = 'SUBMIT_RESUME';

export const SAVE_RESUME = 'SAVE_RESUME';

export const SUBMIT_RESUME_FAILED= 'SUBMIT_RESUME_FAILED';

export const SUBMIT_RESUME_SUCCESS= 'SUBMIT_RESUME_SUCCESS';

export const REQUEST_RESUME_FAILED= 'REQUEST_RESUME_FAILED';

export const REQUEST_RESUME_SUCCESS= 'REQUEST_RESUME_SUCCESS';
